
- name: Hello World Sample
  hosts: all
  tasks:
    - name: install vi
      yum:
        name: vi
        state: latest
    - name: log date into file
      shell: |
        date +"%d-%b-%y  -  %T" >> /tmp/ansible.log
        exit 0
    - name: Message
      debug:
        msg: "TERMINE"
