- hosts: all
  name: Install Tomcat
  
  tasks:
    - name: install Tomcat
      package:
        name: tomcat
        state: present

    - name: start Tomcat
      service:
        name: tomcat
        state: started